services:
  devlegacy:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/sujalgawas/devlegacy/devlegacy:latest
    container_name: devlegacy
    env_file:
      - backend/.env
    volumes:
      - ./backend:/backend
    ports: 
      - "8082:8082"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - tunnel_network
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http devlegacy:8082
    env_file:
      - backend/.env.ngrok
    ports:
      - "4040:4040"
    networks:
      - tunnel_network
    restart: unless-stopped

networks:
  tunnel_network:
    driver: bridge