services:
  db:
    image: postgres:17-alpine
    container_name: devlegacy_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dev
    ports:
      - "5434:5432"
    volumes:
      - devlegacy_postgres_data:/var/lib/postgresql/data
    networks:
      - tunnel_network

  devlegacy:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/sujalgawas/devlegacy/devlegacy:latest
    container_name: devlegacy
    env_file:
      - backend/.env
    environment:
      DATABASE_URL: "postgresql://postgres:1234@db:5432/dev"
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - ./backend:/backend
    ports: 
      - "8082:8082"
    networks:
      - tunnel_network
    depends_on:
      - db
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: devlegacy_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - tunnel_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http devlegacy:8082
    env_file:
      - backend/.env.ngrok
    ports:
      - "4040:4040"
    networks:
      - tunnel_network
    restart: unless-stopped

networks:
  tunnel_network:
    driver: bridge

volumes:
  devlegacy_postgres_data:
