services:
  devlegacy:
    build:
      context: .
      dockerfile: Dockerfile
    #image: "dev/devlegacy:latest"
    container_name: devlegacy
    network_mode: host
    #ports: 
    #  - "8082:8082"
    restart: unless-stopped