"""
codequality.py
==============
Code-quality inference using a quantized GGUF model loaded via llama-cpp-python.
This is designed to run on low-RAM servers (≈ 1.2 GB peak for Q4_K_M 1.5B model).

Model file expected at:
    <backend>/app/.cache/models/model_q4km.gguf

This file is generated by convert_to_gguf.py (run on your PC), then copied to the server.

To change models in the future, update convert_to_gguf.py and re-run it on your PC.
"""

import gc
import json
import logging
import os
import random
from pathlib import Path

from dotenv import load_dotenv

from app.services.prompt import SYSTEM_PROMPT, base_prompt

load_dotenv()

logger = logging.getLogger(__name__)

# ── Model path ────────────────────────────────────────────────────────────────
#
# We anchor to this file's own location (__file__) so the path is always
# correct regardless of the working directory (avoids the ./ confusion
# between running locally vs inside Docker).
#
# __file__  = .../backend/app/services/codequality.py
# .parent   = .../backend/app/services/
# .parent   = .../backend/app/
# .parent   = .../backend/
#                         └─ app/.cache/models/model_q4km.gguf
#
_THIS_FILE  = Path(__file__).resolve()
_APP_DIR    = _THIS_FILE.parent.parent        # .../backend/app
MODEL_DIR   = _APP_DIR / ".cache" / "models"
GGUF_MODEL  = MODEL_DIR / "model_q4km.gguf"

# ── Inference settings (tune to your RAM budget) ──────────────────────────────
N_CTX       = 2048   # context window; lower = less RAM (try 1024 if tight)
N_THREADS   = 4      # CPU threads for inference
N_GPU_LAYERS = 0     # keep at 0 (CPU-only); set > 0 only if you have a GPU

# ── Scoring ───────────────────────────────────────────────────────────────────
SEVERITY_MAP = {"minor": 20, "major": 40, "critical": 60}


# ─────────────────────────────────────────────────────────────────────────────
# Lazy model loading
# We load the model once on first inference, not at import time.
# This avoids crash-at-startup if the .gguf file isn't there yet.
# ─────────────────────────────────────────────────────────────────────────────

_llm = None


def _get_llm():
    """Return the (cached) Llama instance, loading it on first call."""
    global _llm
    if _llm is not None:
        return _llm

    if not GGUF_MODEL.exists():
        raise FileNotFoundError(
            f"GGUF model not found at {GGUF_MODEL}.\n"
            "Run convert_to_gguf.py on your PC to generate it, then copy it to:\n"
            f"  {GGUF_MODEL}"
        )

    try:
        from llama_cpp import Llama
    except ImportError as exc:
        raise ImportError(
            "llama-cpp-python is not installed. "
            "Add 'llama-cpp-python' to requirements.txt and rebuild."
        ) from exc

    logger.info("Loading GGUF model from %s …", GGUF_MODEL)

    _llm = Llama(
        model_path=str(GGUF_MODEL),
        n_ctx=N_CTX,
        n_threads=N_THREADS,
        n_gpu_layers=N_GPU_LAYERS,
        verbose=False,          # set True for debug output
        chat_format="chatml",   # Qwen2.5 uses ChatML format
    )

    logger.info("GGUF model loaded (%.2f GB file).", GGUF_MODEL.stat().st_size / 1e9)
    return _llm


# ─────────────────────────────────────────────────────────────────────────────
# Inference
# ─────────────────────────────────────────────────────────────────────────────

def inference(messages: list, max_new_tokens: int = 256) -> str:
    """
    Run chat inference using the GGUF model.

    Args:
        messages: list of {"role": ..., "content": ...} dicts
        max_new_tokens: max tokens to generate

    Returns:
        Raw string output from the model.
    """
    llm = _get_llm()

    response = llm.create_chat_completion(
        messages=messages,
        max_tokens=max_new_tokens,
        temperature=0.0,        # deterministic
        top_p=1.0,
        repeat_penalty=1.1,     # mild penalty to avoid repetition loops
    )

    return response["choices"][0]["message"]["content"].strip()


# ─────────────────────────────────────────────────────────────────────────────
# Scoring helpers
# ─────────────────────────────────────────────────────────────────────────────

def score_normalize(response: dict) -> int:
    flaws  = response.get("flaws", [])
    score  = 100
    for item in flaws:
        raw_severity = item.get("severity")
        if raw_severity is None:
            continue
        penalty = SEVERITY_MAP.get(str(raw_severity).lower().strip())
        if penalty is not None:
            score -= penalty
    return max(score, 0)


def model_run(code_sample: str):
    """
    Run the model on one code snippet.

    Returns:
        int score (0-100) or None if the model output couldn't be parsed.
    """
    user_message = base_prompt(code_sample)
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user",   "content": user_message},
    ]

    for attempt in range(3):
        raw = inference(messages)
        print(f"[inference] {raw}")
        # Strip markdown fences if model wraps output in ```json ... ```
        cleaned = raw.strip()
        if cleaned.startswith("```"):
            lines = cleaned.splitlines()
            cleaned = "\n".join(
                line for line in lines
                if not line.strip().startswith("```")
            ).strip()

        try:
            candidate = json.loads(cleaned)
            if isinstance(candidate, dict) and "flaws" in candidate:
                return score_normalize(candidate)
            else:
                logger.warning("Attempt %d: unexpected structure: %s", attempt + 1, candidate)
        except (json.JSONDecodeError, TypeError) as exc:
            logger.warning("Attempt %d: parse error (%s), raw=%r", attempt + 1, exc, raw[:200])

    logger.error("model_run: all retries failed, returning None")
    return None


# ─────────────────────────────────────────────────────────────────────────────
# Main public API
# ─────────────────────────────────────────────────────────────────────────────

def code_quality(code):
    """
    Analyse code quality from a dict or list of file snippets.

    Args:
        code: Either a dict mapping repo/language keys to file lists,
              or a plain list of file dicts/strings, or a raw str.
              Each file item should be a dict with a 'content'/'text' key,
              or a plain string.

    Returns:
        (score, level) tuple where score is 0-100 and level is one of
        'Intern', 'Fresher', 'Mid', 'Senior'.
    """
    # Unwrap wrapper dict produced by some fetchers
    if isinstance(code, dict) and "code_data" in code:
        code = code["code_data"]

    code_snippets: list[str] = []

    if isinstance(code, dict):
        for value in code.values():
            if not isinstance(value, list):
                value = [value]
            for file_item in value:
                content = (
                    file_item.get("content") or file_item.get("text") or ""
                    if isinstance(file_item, dict) else str(file_item)
                )
                if content.strip():
                    code_snippets.append(content)

    elif isinstance(code, list):
        for file_item in code:
            content = (
                file_item.get("content") or file_item.get("text") or ""
                if isinstance(file_item, dict) else str(file_item)
            )
            if content.strip():
                code_snippets.append(content)

    elif isinstance(code, str) and code.strip():
        code_snippets.append(code)

    if not code_snippets:
        return 0, "Intern"

    # Sample up to 5 snippets to keep inference time reasonable
    samples = random.sample(code_snippets, min(len(code_snippets), 5))

    scores: list[int] = []
    for snippet in samples:
        # Truncate very long snippets
        truncated = " ".join(snippet.split()[:500])
        result = model_run(truncated)
        if result is not None:
            scores.append(result)

    if not scores:
        return 0, "Intern"

    avg = sum(scores) / len(scores)

    if avg < 30:
        return avg, "Intern"
    elif avg < 50:
        return avg, "Fresher"
    elif avg < 70:
        return avg, "Mid"
    else:
        return avg, "Senior"


# ─────────────────────────────────────────────────────────────────────────────
# Quick manual test
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    sample = """
def add(a, b):
    return a + b

class Calculator:
    def divide(self, a, b):
        return a / b  # no zero-division check
"""
    score, level = code_quality(sample)
    print(f"Score: {score}  Level: {level}")