"""create table code

Revision ID: 165ebd316fdf
Revises: a0ce315122c3
Create Date: 2026-01-27 21:03:09.998858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '165ebd316fdf'
down_revision: Union[str, Sequence[str], None] = 'a0ce315122c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('code', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('document_stats',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('comment_percentage', sa.Integer(), nullable=True),
    sa.Column('comment_to_repos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('documentation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_stats')
    op.drop_table('code')
    # ### end Alembic commands ###
