"""updated table document_stats

Revision ID: 8be820f5a133
Revises: 165ebd316fdf
Create Date: 2026-01-28 01:44:57.413913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8be820f5a133'
down_revision: Union[str, Sequence[str], None] = '165ebd316fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_stats', sa.Column('avg_lines_readme', sa.Integer(), nullable=True))
    op.add_column('document_stats', sa.Column('final_dir', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('document_stats', 'documentation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_stats', sa.Column('documentation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('document_stats', 'final_dir')
    op.drop_column('document_stats', 'avg_lines_readme')
    # ### end Alembic commands ###
