"""create table tech_stack

Revision ID: b576d29773c0
Revises: 2d04a3d09e64
Create Date: 2026-01-24 15:55:44.172649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b576d29773c0'
down_revision: Union[str, Sequence[str], None] = '2d04a3d09e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_stack',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('all_languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('language_with_code_byte', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_stack')
    # ### end Alembic commands ###
