"""create table profile 2

Revision ID: f1004474b147
Revises: 9455e8298a2c
Create Date: 2026-01-23 13:09:28.474258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1004474b147'
down_revision: Union[str, Sequence[str], None] = '9455e8298a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_profile', sa.Column('github_id', sa.Integer(), nullable=True))
    op.drop_column('github_profile', 'gitub_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_profile', sa.Column('gitub_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('github_profile', 'github_id')
    # ### end Alembic commands ###
