"""added user profile in github_profile

Revision ID: 02fdd92158cb
Revises: 4fda321000bc
Create Date: 2026-02-11 19:43:08.071081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fdd92158cb'
down_revision: Union[str, Sequence[str], None] = '4fda321000bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_profile', sa.Column('profile_pic', sa.String(), nullable=True))
    op.drop_column('github_profile', 'uri')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_profile', sa.Column('uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('github_profile', 'profile_pic')
    # ### end Alembic commands ###
