"""profile updated

Revision ID: 43397b5a2132
Revises: 71ad2d74b635
Create Date: 2026-04-20 22:49:25.760669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43397b5a2132'
down_revision: Union[str, Sequence[str], None] = '71ad2d74b635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns('github_profile')]
    if 'recommended_role' not in columns:
        op.add_column('github_profile', sa.Column('recommended_role', sa.String(), nullable=True))
    if 'detected_frameworks' not in columns:
        op.add_column('github_profile', sa.Column('detected_frameworks', sa.String(), nullable=True))
    if 'final_score' not in columns:
        op.add_column('github_profile', sa.Column('final_score', sa.Integer(), nullable=True))
    if 'file_structure' not in columns:
        op.add_column('github_profile', sa.Column('file_structure', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_profile', 'file_structure')
    op.drop_column('github_profile', 'final_score')
    op.drop_column('github_profile', 'detected_frameworks')
    op.drop_column('github_profile', 'recommended_role')
    # ### end Alembic commands ###
