"""added user profile in github_profile

Revision ID: 4fda321000bc
Revises: 8ae0ed460081
Create Date: 2026-02-11 19:36:00.487721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fda321000bc'
down_revision: Union[str, Sequence[str], None] = '8ae0ed460081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_profile', sa.Column('uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_profile', 'uri')
    # ### end Alembic commands ###
