"""resting migration

Revision ID: 71ad2d74b635
Revises: 
Create Date: 2026-03-26 17:10:59.233078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71ad2d74b635'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('code', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('code_quality',
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('commit_status',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('total_commits', sa.Integer(), nullable=True),
    sa.Column('commits_per_repo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('consistency_status',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('total_contributions', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('active_days', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('document_stats',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('avg_lines_readme', sa.Integer(), nullable=True),
    sa.Column('comment_percentage', sa.Integer(), nullable=True),
    sa.Column('comment_to_repos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_dir', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('github_profile',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('github_profile', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_repo', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('open_source',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('pull_requests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repositories_contributed_to', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('code_reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('tech_stack',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('all_languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('language_with_code_byte', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('testing',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('temp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('temp')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('testing')
    op.drop_table('tech_stack')
    op.drop_table('open_source')
    op.drop_table('github_profile')
    op.drop_table('document_stats')
    op.drop_table('consistency_status')
    op.drop_table('commit_status')
    op.drop_table('code_quality')
    op.drop_table('code')
    # ### end Alembic commands ###
