"""create table profile

Revision ID: 9455e8298a2c
Revises: d6d14cdc8e08
Create Date: 2026-01-23 12:58:23.933928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9455e8298a2c'
down_revision: Union[str, Sequence[str], None] = 'd6d14cdc8e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_profile',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('gitub_id', sa.Integer(), nullable=True),
    sa.Column('github_profile', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('public_repo', sa.Integer(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('following', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_profile')
    # ### end Alembic commands ###
