"""code updated

Revision ID: ab55f5739f5b
Revises: 72f18f961f0f
Create Date: 2026-04-21 05:26:21.465887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab55f5739f5b'
down_revision: Union[str, Sequence[str], None] = '72f18f961f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_quality', sa.Column('code_score', sa.Integer(), nullable=True))
    op.add_column('code_quality', sa.Column('code_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_quality', 'code_level')
    op.drop_column('code_quality', 'code_score')
    # ### end Alembic commands ###
