"""create commit_status 2

Revision ID: d6d14cdc8e08
Revises: 7be4bbbe3301
Create Date: 2026-01-23 11:42:49.364257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6d14cdc8e08'
down_revision: Union[str, Sequence[str], None] = '7be4bbbe3301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commit_status',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('total_commits', sa.Integer(), nullable=True),
    sa.Column('commits_per_repo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commit_status')
    # ### end Alembic commands ###
