"""create table open_source

Revision ID: f4ab24831cac
Revises: b576d29773c0
Create Date: 2026-01-24 21:06:17.605147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4ab24831cac'
down_revision: Union[str, Sequence[str], None] = 'b576d29773c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_source',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('pull_requests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repositories_contributed_to', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('code_reviews', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_source')
    # ### end Alembic commands ###
