"""table code_quality created

Revision ID: f8bc1798eef9
Revises: 02fdd92158cb
Create Date: 2026-03-11 10:32:59.882784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8bc1798eef9'
down_revision: Union[str, Sequence[str], None] = '02fdd92158cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_quality',
    sa.Column('uid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_quality')
    # ### end Alembic commands ###
